import { NextRequest, NextResponse } from 'next/server';
import { getUserFromRequest } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

/**
 * GET /api/reports
 * Get reports based on user role
 */
export async function GET(req: NextRequest) {
  try {
    const user = getUserFromRequest(req);

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const role = user.role.toUpperCase();

    // Staff cannot access reports
    if (role === 'STAFF') {
      return NextResponse.json(
        { error: 'Staff members cannot access reports' },
        { status: 403 }
      );
    }

    let reports;

    if (role === 'ADMIN') {
      // Admin can see all reports
      reports = await prisma.report.findMany({
        include: {
          generator: {
            select: {
              id: true,
              username: true,
              email: true,
              staff: {
                select: {
                  staffName: true,
                  department: {
                    select: {
                      departmentName: true,
                    },
                  },
                },
              },
            },
          },
          meeting: {
            select: {
              id: true,
              meetingTitle: true,
              meetingDate: true,
            },
          },
        },
        orderBy: { generatedAt: 'desc' },
      });
    } else if (role === 'CONVENER') {
      // Convener can only see reports for their own meetings
      reports = await prisma.report.findMany({
        where: {
          OR: [
            // Reports generated by convener
            { generatedBy: user.userId },
            // Reports from meetings organized by convener
            {
              meeting: {
                organizerStaffId: user.staffId,
              },
            },
          ],
        },
        include: {
          generator: {
            select: {
              id: true,
              username: true,
              staff: {
                select: {
                  staffName: true,
                },
              },
            },
          },
          meeting: {
            select: {
              id: true,
              meetingTitle: true,
              meetingDate: true,
            },
          },
        },
        orderBy: { generatedAt: 'desc' },
      });
    }

    // Transform the data to match frontend interface
    const transformedReports = reports?.map((report) => ({
      id: report.id,
      reportName: report.reportName,
      reportType: report.reportType.toLowerCase().replace('_', '-'),
      fileUrl: report.filePath,
      createdAt: report.generatedAt,
      generatedBy: report.generator
        ? {
            username: report.generator.username,
            staff: report.generator.staff
              ? {
                  staffName: report.generator.staff.staffName,
                }
              : undefined,
          }
        : undefined,
      meeting: report.meeting
        ? {
            meetingTitle: report.meeting.meetingTitle,
            meetingDate: report.meeting.meetingDate,
          }
        : undefined,
    }));

    return NextResponse.json({
      success: true,
      reports: transformedReports || [],
    });
  } catch (error) {
    console.error('Error fetching reports:', error);
    return NextResponse.json(
      { error: 'Failed to fetch reports' },
      { status: 500 }
    );
  }
}
