'use client';

import { motion, AnimatePresence } from 'framer-motion';
import { X, Download, Calendar, User, FileText, Building2 } from 'lucide-react';

interface Report {
  id: number;
  reportName: string;
  reportType: string;
  fileUrl: string;
  createdAt: Date;
  generatedBy?: {
    username: string;
    staff?: {
      staffName: string;
    };
  };
  meeting?: {
    meetingTitle: string;
    meetingDate: Date;
  };
  department?: {
    departmentName: string;
  };
}

interface ReportPreviewDrawerProps {
  report: Report | null;
  isOpen: boolean;
  onClose: () => void;
}

export default function ReportPreviewDrawer({
  report,
  isOpen,
  onClose,
}: ReportPreviewDrawerProps) {
  if (!report) return null;

  // fileUrl may be a relative path like /api/reports/5/download?...
  // Resolve to an absolute URL so iframe and window.open both work
  const absoluteUrl =
    typeof window !== 'undefined' && report.fileUrl.startsWith('/')
      ? `${window.location.origin}${report.fileUrl}`
      : report.fileUrl;

  const handleDownload = () => {
    window.open(absoluteUrl, '_blank');
  };

  const formatReportType = (type: string) => {
    return type
      .split('-')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black bg-opacity-50 z-40"
          />

          {/* Drawer */}
          <motion.div
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'spring', damping: 25, stiffness: 200 }}
            className="fixed right-0 top-0 bottom-0 w-full md:w-2/3 lg:w-1/2 bg-white shadow-2xl z-50 flex flex-col"
          >
            {/* Header */}
            <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between bg-gradient-to-r from-blue-600 to-purple-600">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center shadow-sm">
                  <FileText className="w-5 h-5 text-blue-600" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-white">Report Preview</h2>
                  <p className="text-sm text-blue-100">{report.reportName}</p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 hover:bg-white hover:bg-opacity-20 rounded-lg transition-colors"
              >
                <X className="w-5 h-5 text-white" />
              </button>
            </div>

            {/* Metadata */}
            <div className="px-6 py-4 bg-gray-50 border-b border-gray-200">
              <div className="grid grid-cols-2 gap-4">
                <div className="flex items-start gap-3">
                  <div className="w-8 h-8 bg-purple-100 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5">
                    <FileText className="w-4 h-4 text-purple-600" />
                  </div>
                  <div>
                    <p className="text-xs text-gray-500 uppercase tracking-wide">Type</p>
                    <p className="text-sm font-medium text-gray-900">
                      {formatReportType(report.reportType)}
                    </p>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5">
                    <Calendar className="w-4 h-4 text-blue-600" />
                  </div>
                  <div>
                    <p className="text-xs text-gray-500 uppercase tracking-wide">Generated</p>
                    <p className="text-sm font-medium text-gray-900">
                      {new Date(report.createdAt).toLocaleDateString()}
                    </p>
                  </div>
                </div>

                {report.generatedBy && (
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5">
                      <User className="w-4 h-4 text-green-600" />
                    </div>
                    <div>
                      <p className="text-xs text-gray-500 uppercase tracking-wide">Generated By</p>
                      <p className="text-sm font-medium text-gray-900">
                        {report.generatedBy.staff?.staffName || report.generatedBy.username}
                      </p>
                    </div>
                  </div>
                )}

                {report.meeting && (
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 bg-orange-100 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5">
                      <Calendar className="w-4 h-4 text-orange-600" />
                    </div>
                    <div>
                      <p className="text-xs text-gray-500 uppercase tracking-wide">Meeting</p>
                      <p className="text-sm font-medium text-gray-900">
                        {report.meeting.meetingTitle}
                      </p>
                    </div>
                  </div>
                )}

                {report.department && (
                  <div className="flex items-start gap-3 col-span-2">
                    <div className="w-8 h-8 bg-indigo-100 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5">
                      <Building2 className="w-4 h-4 text-indigo-600" />
                    </div>
                    <div>
                      <p className="text-xs text-gray-500 uppercase tracking-wide">Department</p>
                      <p className="text-sm font-medium text-gray-900">
                        {report.department.departmentName}
                      </p>
                    </div>
                  </div>
                )}
              </div>

              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleDownload}
                className="mt-4 w-full px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium flex items-center justify-center gap-2"
              >
                <Download className="w-4 h-4" />
                Download Report
              </motion.button>
            </div>

            {/* PDF Preview */}
            <div className="flex-1 overflow-hidden bg-gray-100">
              <iframe
                src={absoluteUrl}
                className="w-full h-full border-0"
                title="Report Preview"
              />
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
